name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Run tests
        run: sbt test

      - name: Build Native Executable
        run: sbt 'show GraalVMNativeImage/packageBin'

      - name: Test Run
        shell: bash
        run: |
          target/graalvm-native-image/fanhuaji-cli -v -i test-files/chs.ass -m Taiwan test-files/result.ass
          diff --strip-trailing-cr -I 'Comment: Processed by 繁化姬' test-files/cht.ass test-files/result.ass